pipeline:
  build:
    image: docker.io/texlive/texlive
    commands:
    - export ARTIFACT_DIR=$CI_WORKSPACE/.artifacts/$CI_REPO_NAME/$CI_BRANCH/$CI_BUILD_NUMBER/
    - mkdir -p $ARTIFACT_DIR
    - pdflatex "\PassOptionsToPackage{$STATUS,$CROP}{llncsconf}\input{example.tex}"
    - pdflatex "\PassOptionsToPackage{$STATUS,$CROP}{llncsconf}\input{example.tex}" 
    - cp example.pdf $ARTIFACT_DIR/example_${STATUS}_${CROP}.pdf
    - find $ARTIFACT_DIR
    - cd $ARTIFACT_DIR
    - cd ..
    - ln -s * latest
    - sleep 5
  deploy:
    image: docker.io/drillster/drone-rsync
    settings:
      hosts: [ "ci.logicalhacking.com"]
      port: 22
      source: .artifacts/$CI_REPO_NAME/*
      target: $CI_REPO_NAME
      include: [ "**.*"]
      key: 
        from_secret: artifacts_ssh
      user: artifacts

matrix:
  CROP:
    - nocrop
    - crop
  STATUS:
    - intended
    - submitted
    - accepted
    - proceedings
    - llncs
