on:
  push:
  workflow_dispatch:
concurrency:
  group: check
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: localhost:5000/name/app:latest
          file: test/Dockerfile
      - name: Set up Git repository
        uses: actions/checkout@v3
      - run: |
          mkdir /tmp/out
          mkdir /tmp/res

          # use latest development verison for testing
          cp llncsconf.sty test
      - name: example-intended
        run: docker run -v $(pwd)/test:/work/src -v /tmp/out:/work/out localhost:5000/name/app:latest work "pdflatex example-intended.tex"
      - run: mv /tmp/out/*.pdf /tmp/res
      - name: example-submitted
        run: docker run -v $(pwd)/test:/work/src -v /tmp/out:/work/out localhost:5000/name/app:latest work "pdflatex example-submitted.tex"
      - run: mv /tmp/out/*.pdf /tmp/res
      - name: example-accepted
        run: docker run -v $(pwd)/test:/work/src -v /tmp/out:/work/out localhost:5000/name/app:latest work "pdflatex example-accepted.tex"
      - run: mv /tmp/out/*.pdf /tmp/res
      - name: example-proceedings
        run: docker run -v $(pwd)/test:/work/src -v /tmp/out:/work/out localhost:5000/name/app:latest work "pdflatex example-proceedings.tex"
      - run: mv /tmp/out/*.pdf /tmp/res
      - name: example-lncs
        run: docker run -v $(pwd)/test:/work/src -v /tmp/out:/work/out localhost:5000/name/app:latest work "pdflatex example-lncs.tex"
      - run: mv /tmp/out/*.pdf /tmp/res
      - uses: actions/upload-artifact@v2
        with:
          name: test-result
          path: |
            /tmp/res/*.pdf
